### ISSUE TITLE
Flux vs Redux vs Mobx

### ISSUE THREAD

**Issue by ac-opensource** [platf0rm/platform#17]

**Comment by kimerran** [comment]
I'd give more weight to the one choosen by those who wants to learn that specific library.
Personally I'd vote for redux just for the reason that it is the common partner for react.js

**Comment by makoru-hikage** [comment]
I vote for Redux

**Comment by ghost** [comment]
Although I love the simplicity of Reflux and the rockstar vibes of Alt, I'd vote for Redux since it is the one usually used with React.

**Comment by kimerran** [comment]
it's a majority vote. closing this issue. Redux wins.
