### ISSUE TITLE
What library shall be used for server-side validation?

### ISSUE THREAD

**Issue by hyalina** [platf0rm/platform#4]
Also, how shall the validation be?

**Comment by kimerran** [comment]
I have opened an [issue](https://github.com/platf0rm/platform/issues/6) to use Sequelize as the ORM for the data layer.

**Comment by hyalina** [comment]
The ORM is irrelevant unless it has form validation as a feature. What I meant by validation is:

"Username is already taken, please input another"
"This is not a valid email address"
"Username must only contain alphanumeric characters and _"
"Password must be 8-20 characters in length"

**Comment by kimerran** [comment]
Sequelize and some ORMs can actually handle the validation. see [this](http://docs.sequelizejs.com/en/latest/docs/models-definition/)

**Comment by hyalina** [comment]
It's decided
