### ISSUE TITLE
ORM for the PostgreSQL database

### ISSUE THREAD

**Issue by kimerran** [platf0rm/platform#6]
I have seen recommendations to use [Sequelize](http://docs.sequelizejs.com/en/v3/) as an ORM for PostgreSQL in node.js. Thoughts?

example usage:
```
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'username', 'password');

var User = sequelize.define('user', {
  username: Sequelize.STRING,
  birthday: Sequelize.DATE
});

sequelize.sync().then(function() {
  return User.create({
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  });
}).then(function(jane) {
  console.log(jane.get({
    plain: true
  }));
});
```

**Comment by hyalina** [comment]
Should this library be stable and still rolling and still used by many dev, then yes. Let's consult others.

**Comment by ghost** [comment]
Should we go for more magic and new or stable and mature? I'm fine with Sequelize but I'd like to hear what you think about it after hearing or reading recommendations to use this over other ORM.

**Comment by kimerran** [comment]
alright let's use Sequelize. If there's something Sequelize can't handle, I'd be happy to re-write, 🤣
