### ISSUE TITLE
Request to move web source to platform-web-ui project

### ISSUE THREAD

**Issue by kimerran** [platf0rm/platform#7]
Please move [source](https://github.com/platf0rm/platform/tree/master/src) to the [web-ui project](https://github.com/platf0rm/platform-web-ui).

This repository should only contain docs and specs and issues related to those

**Comment by kimerran** [comment]
@hyalina fya. thanks

**Comment by hyalina** [comment]
@Temoto-kun,, do the honors.

**Comment by TheoryOfNekomata** [comment]
Done.
